'''
This file contains hard coded stops with neighbours and which lines pass through the stops
'''
lines = {"light-blue": "Ashton-Eccles", 
         "pink": "Rochdale-Didsbury",
         "green": "Altrincham-Bury",
         "purple": "Altrincham-Piccadilly",
         "yellow": "Bury-Piccadilly",
         #"DS": "Didsbury-Shaw", # sort of a sub-line of
         "blue": "Airport-Victoria",
         "red": "Trafford-Deansgate"}

# i ignore the grey and orange lines

graph = {"Heaton Park":[["Bowker Vale","Prestwich"], ["yellow", "green"]],
    "Bowker Vale":[["Heaton Park","Crumpsall"], ["yellow", "green"]],
    "Crumpsall":[["Bowker Vale","Abraham Moss"], ["yellow", "green"]],
    "Bury":[["Radcliffe"], ["yellow", "green"]],
    "Radcliffe":[["Bury","Whitefield"], ["yellow", "green"]],
    "Whitefield":[["Besses o' th' Barn","Radcliffe"], ["yellow", "green"]],
    "Besses o' th' Barn":[["Prestwich","Whitefield"], ["yellow", "green"]],
    "Prestwich":[["Heaton Park","Besses o' th' Barn"], ["yellow", "green"]],
    "Victoria":[["Shudehill","Exchange Square","Monsall","Queens Road"], ["yellow", "green", "blue"]],
    "Market Street":[["Shudehill","Piccadilly Gardens","St Peter's Square"], ["yellow", "green", "blue"]],
    "Piccadilly Gardens":[["Market Street","St Peter's Square","Piccadilly","Exchange Square"], ["yellow", "purple", "light-blue"]],
    "Piccadilly":[["New Islington","Piccadilly Gardens"], ["yellow", "purple", "light-blue"]],
    "Deansgate-Castlefield":[["Cornbrook","St Peter's Square"], ["red", "light-blue", "purple", "green", "blue", "pink"]],
    "Pomona":[["Wharfside","Exchange Quay","Cornbrook"], ["red", "light-blue"]],
    "Trafford Bar":[["Old Trafford","Cornbrook","Firswood"], ["purple", "green", "blue", "pink"]],
    "Shudehill":[["Market Street","Victoria"], ["yellow", "green", "blue"]],
    "Firswood":[["Trafford Bar","Chorlton"], ["blue", "pink"]],
    "Chorlton":[["Firswood","St Werburgh's Road"], ["blue", "pink"]],
    "St Werburgh's Road":[["Barlow Moor Road","Withington","Chorlton"], ["blue", "pink"]],
    "Sale Water Park":[["Barlow Moor Road","Northern Moor"], ["blue"]],
    "Northern Moor":[["Wythenshawe Park","Sale Water Park"], ["blue"]],
    "Wythenshawe Park":[["Moor Road","Northern Moor"], ["blue"]],
    "Moor Road":[["Wythenshawe Park","Baguley"], ["blue"]],
    "Baguley":[["Roundthorn","Moor Road"], ["blue"]],
    "Roundthorn":[["Baguley","Martinscroft"], ["blue"]],
    "Martinscroft":[["Roundthorn","Benchill"], ["blue"]],
    "Benchill":[["Crossacres","Martinscroft"], ["blue"]],
    "Crossacres":[["Wythenshawe Town Centre","Benchill"], ["blue"]],
    "Robinswood Road":[["Wythenshawe Town Centre","Peel Hall"], ["blue"]],
    "Peel Hall":[["Robinswood Road","Shadowmoss"], ["blue"]],
    "Shadowmoss":[["Manchester Airport","Peel Hall"], ["blue"]],
    "Manchester Airport":[["Shadowmoss"], ["blue"]],
    "New Islington":[["Piccadilly","Holt Town"], ["light-blue"]],
    "Holt Town":[["New Islington","Etihad Campus"], ["light-blue"]],
    "Etihad Campus":[["Velopark","Holt Town"], ["light-blue"]],
    "Velopark":[["Clayton Hall","Etihad Campus"], ["light-blue"]],
    "Clayton Hall":[["Edge Lane","Velopark"], ["light-blue"]],
    "Edge Lane":[["Clayton Hall","Cemetery Road"], ["light-blue"]],
    "Cemetery Road":[["Droylsden","Edge Lane"], ["light-blue"]],
    "Droylsden":[["Cemetery Road","Audenshaw"], ["light-blue"]],
    "Audenshaw":[["Droylsden","Ashton Moss"], ["light-blue"]],
    "Ashton Moss":[["Ashton West","Audenshaw"], ["light-blue"]],
    "Ashton West":[["Ashton Moss","Ashton-under-Lyne"], ["light-blue"]],
    "Ashton-under-Lyne":[["Ashton West"], ["light-blue"]],
    "Queens Road":[["Shudehill","Abraham Moss"], ["yellow", "green"]],
    "Monsall":[["Central Park","Victoria"], ["pink"]],
    "Central Park":[["Newton Heath and Moston","Monsall"], ["pink"]],
    "Newton Heath and Moston":[["Central Park","Failsworth"], ["pink"]],
    "Failsworth":[["Newton Heath and Moston","Hollinwood"], ["pink"]],
    "Hollinwood":[["Failsworth","South Chadderton"], ["pink"]],
    "South Chadderton":[["Freehold","Hollinwood"], ["pink"]],
    "Cornbrook":[["Deansgate-Castlefield","Pomona","Trafford Bar"], ["red", "light-blue", "purple", "green", "blue", "pink"]],
    "Abraham Moss":[["Crumpsall","Queens Road"], ["green", "yellow"]],
    "Dane Road":[["Sale","Stretford"], ["purple", "green"]],
    "Sale":[["Brooklands","Dane Road"], ["purple", "green"]],
    "Brooklands":[["Sale","Timperley"], ["purple", "green"]],
    "Timperley":[["Navigation Road","Brooklands"], ["purple", "green"]],
    "Navigation Road":[["Timperley","Altrincham"], ["purple", "green"]],
    "Altrincham":[["Navigation Road"], ["purple", "green"]],
    "Eccles":[["Ladywell"], ["light-blue"]],
    "Ladywell":[["Weaste","Eccles"], ["light-blue"]],
    "Salford Quays":[["Anchorage","Exchange Quay"], ["light-blue"]],
    "Exchange Quay":[["Pomona","Salford Quays"], ["light-blue"]],
    "Harbour City":[["Broadway","MediaCityUK","Anchorage"], ["light-blue"]],
    "Anchorage":[["Harbour City","Salford Quays"], ["light-blue"]],
    "Broadway":[["MediaCityUK","Harbour City","Langworthy"], ["light-blue"]],
    "Langworthy":[["Weaste","Broadway"], ["light-blue"]],
    "Weaste":[["Ladywell","Langworthy"], ["light-blue"]],
    "Old Trafford":[["Stretford","Trafford Bar"], ["purple", "green"]],
    "Stretford":[["Old Trafford","Dane Road"], ["purple", "green"]],
    "MediaCityUK":[["Harbour City","Broadway"], ["light-blue"]],
    "Freehold":[["Westwood","South Chadderton"], ["pink"]],
    "Oldham King Street":[["Westwood","Oldham Central"], ["pink"]],
    "Oldham Central":[["Oldham Mumps","Oldham King Street"], ["pink"]],
    "Oldham Mumps":[["Oldham Central","Derker"], ["pink"]],
    "Derker":[["Oldham Mumps","Shaw and Crompton"], ["pink"]],
    "Shaw and Crompton":[["Derker","Newhey"], ["pink"]],
    "Newhey":[["Milnrow","Shaw and Crompton"], ["pink"]],
    "Milnrow":[["Kingsway Business Park","Newhey"], ["pink"]],
    "Kingsway Business Park":[["Milnrow","Newbold"], ["pink"]],
    "Newbold":[["Kingsway Business Park","Rochdale Railway Station"], ["pink"]],
    "Rochdale Railway Station":[["Rochdale Town Centre","Newbold"], ["pink"]],
    "Rochdale Town Centre":[["Rochdale Railway Station"], ["pink"]],
    "Barlow Moor Road":[["Sale Water Park","St Werburgh's Road"], ["blue"]],
    "Withington":[["St Werburgh's Road","Burton Road"], ["pink"]],
    "Burton Road":[["Withington","West Didsbury"], ["pink"]],
    "West Didsbury":[["Didsbury Village","Burton Road"], ["pink"]],
    "Didsbury Village":[["East Didsbury","West Didsbury"], ["pink"]],
    "East Didsbury":[["Didsbury Village"], ["pink"]],
    "Wythenshawe Town Centre":[["Robinswood Road","Crossacres"], ["blue"]],
    "Westwood":[["Oldham King Street","Freehold"], ["pink"]],
    "Exchange Square":[["St Peter's Square","Victoria"], ["light-blue", "purple", "green", "blue", "pink"]],
    "The Trafford Centre":[["Barton Dock Road"], ["red"]],
    "Wharfside":[["Imperial War Museum", "Pomona"], ["red"]],
    "Imperial War Museum":[["Village","Wharfside"], ["red"]],
    "Village":[["Imperial War Museum","Parkway"], ["red"]],
    "Parkway":[["Barton Dock Road","Village"], ["red"]],
    "Barton Dock Road":[["Parkway","The Trafford Centre"], ["red"]],
    "St Peter's Square":[["Deansgate-Castlefield","Exchange Square","Piccadilly Gardens","Market Street"], ["light-blue", "purple", "green", "blue", "pink"]]
    }

if __name__ == "__main__":
    print({k: ["topoX", "topoY"] for k in graph.keys()})
