"""
Metrodle — FastAPI Backend
==========================
Responsibilities:
  - GET  /api/daily          → today's target stop (deterministic, date-seeded)
  - POST /api/stats           → persist a completed game result
  - GET  /api/stats/{player}  → retrieve stats for a player
  - GET  /health              → Railway health check

All graph logic, BFS, and game UI live in the React frontend.
Stats are stored in SQLite (persisted to a Railway volume at /data).
"""

import hashlib
import json
import os
import sqlite3
from contextlib import asynccontextmanager
from datetime import date, timezone, datetime
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# ─── Config ───────────────────────────────────────────────────────────────────

# Railway: mount a volume at /data for persistence.
# Locally: falls back to ./data/
DATA_DIR = Path(os.getenv("DATA_DIR", "./data"))
DB_PATH  = DATA_DIR / "metrodle.db"

# Comma-separated list of allowed origins — set in Railway env vars.
# Locally defaults to Vite dev server.
ALLOWED_ORIGINS = os.getenv(
    "ALLOWED_ORIGINS",
    "http://localhost:5173,http://localhost:3000"
).split(",")

# ─── Stop list (used for daily target selection) ──────────────────────────────
# We embed just the stop names here so the backend is self-contained.
# The full graph + coordinates stay in the frontend bundle.
STOPS_FILE = Path(__file__).parent / "stops.json"

def load_stops() -> list[str]:
    """Load stop names from stops.json (generated by build_graph.py)."""
    if not STOPS_FILE.exists():
        raise RuntimeError(
            f"stops.json not found at {STOPS_FILE}. "
            "Run build_graph.py and copy stops.json into the backend folder."
        )
    with open(STOPS_FILE) as f:
        data = json.load(f)
    # stops.json can be either a list of names or the full graph JSON
    if isinstance(data, list):
        return data
    if isinstance(data, dict) and "stops" in data:
        return list(data["stops"].keys())
    raise ValueError("Unexpected stops.json format")

# ─── Daily target logic ───────────────────────────────────────────────────────

def get_daily_stop(stops: list[str], for_date: date | None = None) -> dict:
    """
    Deterministic daily stop selection.
    Uses a SHA-256 hash of the ISO date string so the sequence is
    unpredictable but reproducible — same answer worldwide all day.
    """
    d = for_date or date.today()
    digest = hashlib.sha256(d.isoformat().encode()).hexdigest()
    index  = int(digest[:8], 16) % len(stops)
    return {
        "stop":       stops[index],
        "date":       d.isoformat(),
        "stop_index": index,       # useful for debugging
    }

# ─── Database ─────────────────────────────────────────────────────────────────

def get_db() -> sqlite3.Connection:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    with get_db() as conn:
        conn.executescript("""
            CREATE TABLE IF NOT EXISTS game_results (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                player_id   TEXT    NOT NULL,
                date        TEXT    NOT NULL,
                won         INTEGER NOT NULL,   -- 1 = win, 0 = loss
                guesses     INTEGER NOT NULL,   -- number of guesses used
                target_stop TEXT    NOT NULL,
                created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
                UNIQUE(player_id, date)         -- one result per player per day
            );

            CREATE INDEX IF NOT EXISTS idx_player ON game_results(player_id);
            CREATE INDEX IF NOT EXISTS idx_date   ON game_results(date);
        """)

# ─── Lifespan ─────────────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    init_db()
    app.state.stops = load_stops()
    yield

# ─── App ──────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Metrodle API",
    description="Backend for Metrodle — Manchester Metrolink Wordle",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# ─── Schemas ──────────────────────────────────────────────────────────────────

class GameResult(BaseModel):
    player_id:   str  = Field(..., min_length=1, max_length=64,
                               description="Anonymous client-generated UUID")
    date:        str  = Field(..., pattern=r"^\d{4}-\d{2}-\d{2}$",
                               description="ISO date string YYYY-MM-DD")
    won:         bool
    guesses:     int  = Field(..., ge=1, le=8)
    target_stop: str  = Field(..., min_length=1, max_length=64)


class PlayerStats(BaseModel):
    player_id:       str
    games_played:    int
    games_won:       int
    win_rate:        float
    current_streak:  int
    max_streak:      int
    guess_distribution: dict[str, int]   # {"1": n, "2": n, ..., "8": n}


# ─── Routes ───────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    return {"status": "ok", "db": str(DB_PATH)}


@app.get("/api/daily")
def daily_stop():
    """
    Returns today's target stop name.
    The frontend uses this to validate guesses and show the reveal.
    """
    return get_daily_stop(app.state.stops)


@app.get("/api/daily/{iso_date}")
def daily_stop_for_date(iso_date: str):
    """Returns the target stop for any given date (YYYY-MM-DD). Useful for testing."""
    try:
        d = date.fromisoformat(iso_date)
    except ValueError:
        raise HTTPException(400, "Invalid date format. Use YYYY-MM-DD.")
    return get_daily_stop(app.state.stops, d)


@app.post("/api/stats", status_code=201)
def record_result(result: GameResult):
    """
    Record the outcome of a completed game.
    Idempotent — submitting the same player+date again is a no-op.
    """
    try:
        date.fromisoformat(result.date)
    except ValueError:
        raise HTTPException(400, "Invalid date.")

    with get_db() as conn:
        try:
            conn.execute(
                """INSERT OR IGNORE INTO game_results
                   (player_id, date, won, guesses, target_stop)
                   VALUES (?, ?, ?, ?, ?)""",
                (result.player_id, result.date,
                 int(result.won), result.guesses, result.target_stop),
            )
        except sqlite3.Error as e:
            raise HTTPException(500, f"DB error: {e}")

    return {"status": "ok"}


@app.get("/api/stats/{player_id}", response_model=PlayerStats)
def get_stats(player_id: str):
    """Return aggregated stats for a player."""
    with get_db() as conn:
        rows = conn.execute(
            """SELECT date, won, guesses
               FROM game_results
               WHERE player_id = ?
               ORDER BY date ASC""",
            (player_id,),
        ).fetchall()

    if not rows:
        # Return zeroed stats rather than 404 — cleaner for first-time players
        return PlayerStats(
            player_id=player_id,
            games_played=0, games_won=0, win_rate=0.0,
            current_streak=0, max_streak=0,
            guess_distribution={str(i): 0 for i in range(1, 9)},
        )

    games_played = len(rows)
    games_won    = sum(1 for r in rows if r["won"])
    win_rate     = round(games_won / games_played * 100, 1) if games_played else 0.0

    # Guess distribution (only winning games count)
    dist = {str(i): 0 for i in range(1, 9)}
    for r in rows:
        if r["won"]:
            dist[str(r["guesses"])] = dist.get(str(r["guesses"]), 0) + 1

    # Streak calculation (consecutive calendar days)
    dates = sorted(r["date"] for r in rows)
    current_streak = max_streak = streak = 0
    prev = None
    for ds in dates:
        d = date.fromisoformat(ds)
        if prev and (d - prev).days == 1:
            streak += 1
        elif prev and (d - prev).days > 1:
            streak = 1
        else:
            streak = 1
        max_streak = max(max_streak, streak)
        prev = d

    # Is the streak still alive today or yesterday?
    today = date.today()
    last  = date.fromisoformat(dates[-1])
    current_streak = streak if (today - last).days <= 1 else 0

    return PlayerStats(
        player_id=player_id,
        games_played=games_played,
        games_won=games_won,
        win_rate=win_rate,
        current_streak=current_streak,
        max_streak=max_streak,
        guess_distribution=dist,
    )
